---
- name: Agnostic Net Example
  hosts: arista_switches
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_ssh_pass: alta3

  tasks:
      # Run a show run command and save what is returned by the command as results
    - name: run show version on remote devices
      ansible.netcommon.cli_command:
          command: "{{ item }}"        
      loop:  
        - show version
        - show interfaces
      register: results

      # Print out the variable results
      #    - name: print out what is returned by show version
      #      debug:
      #       var: results.results[1]   #list (results[1])) in a dictionary results (results)


    - name: take a peek as to what is inside of "results"
      debug:
                    var: results

    - name: take a peek at "just" the JSON returned to the command "show version"
      debug:
                    var: results.results[0]

    - name: take a peek at "just" the JSON returned to the command "show interfaces"
      debug:
                    var: results.results[1]
